### ISSUE TITLE
double NIS domain line is created

### ISSUE THREAD

**Issue by A1ve5** [CSC-IT-Center-for-Science/ansible-role-nis#3]
on /etc/sysconfig/network
NISDOMAIN=fgci.csc.fi
NISDOMAIN="fgci.csc.fi"

Not clear what's the impact for now

**Comment by martbhell** [comment]
I think this can be fixed by sorting out the quotes.

First attempt: cb9b5acafa0b425beff1777cc41b9ec5de351659

Which entry is best?

> NISDOMAIN=fgci.csc.fi

or

> NISDOMAIN="fgci.csc.fi"
